Monitor External Installation REFRESHES FFF EEE: TTTT
EEE add note to not include dots in the name

I had to remove __renaming_type to use new_name() - it made me uneasy
since I wrote it, to replace existing logic (double underscore usually
means _revisit_) - very dangerous to leave it in there. Performance to
get the selected items should be negligible - it's still ugly, we should
find a way to absorb this into the Installer* classes - under # 259.
Note the ugliness of `to_rename and...`, due to the method being called
in MEI where there are no selected items in the ui list.
Using self.window.new_name in there allowed me to absorb the
`bass.dirs['installers']` into createFromData where it belongs - not
sure why we use projectName.root, dropped as I don't deal with Paths
here - had to add GPath calls in new_name.
From future: no need to call list() - directly use sorted(), some
wrapping.

Monkey patch for monitor external not detecting new project:

https://bethesda.net/community/post/344453:

Traceback (most recent call last):
  File "bash\balt.py", line 2490, in __Execute
    self.Execute()
  File "bash\balt.py", line 1602, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\installers_links.py", line 170, in Execute
    override=False)
  File "bash\bosh\bain.py", line 2297, in bain_install
    override)
  File "bash\bosh\bain.py", line 2222, in _install
    self.moveArchives(packages, len(self))
  File "bash\bosh\bain.py", line 2114, in moveArchives
    new_ordered = self.sorted_values(moveList)
  File "bash\bosh\bain.py", line 2291, in sorted_values
    else: pairs = [self[k] for k in package_keys]
  File "bash\bolt.py", line 1291, in __getitem__
    return self.data[key]
KeyError: bolt.Path(u'Bodyslide-BookofUUNP-20170513')

Monkey patch:

@@ -160,2 +160,3 @@ def Execute(self):
         # Refresh Installers - so we can manipulate the InstallerProject item
+        self.iPanel.frameActivated = True # yak, refresh data directly here
         self.iPanel.ShowPanel()

Monkey patch in the sense that we should call a targeted refresh, just
adding the new project - done later. frameActivated is a smell but
still needed.